baseURL = 'https://solerf.github.io/'
languageCode = 'en-us'
title = 'Recordings'
summaryLength = 20

# keep taxonomy to show tags
# disableKinds = ["term", "section"]
# as taxonomy is kept, it will get a console error message
# ignoreErrors = ["error-disable-taxonomy"]

[params]
    author = "solerf"
    maxNotes = 20

[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 2

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    style = 'doom-one2'
    wrapperClass = 'highlight'

