baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Recordings'
summaryLength = 20

[params]
    author = "solerf"
    maxNotes = 20

[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'Search'
    pageRef = '/search'
    weight = 2

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    style = 'doom-one2'
    wrapperClass = 'highlight'
